### ISSUE TITLE
[ios] problem building on iPhone

### ISSUE THREAD

**Issue by Bickson** [lazaronixon/react-native-turbolinks#10]
@lazaronixon Does anything need to be done for building project on a phone?
anyone else encountered this?
<img width="1442" alt="screen shot 2018-03-14 at 10 16 09" src="https://user-images.githubusercontent.com/946680/37393359-26d2e882-2771-11e8-890a-c9b06552accc.png">

thanks!

**Comment by lazaronixon** [comment]
Are you did this step?
### Installation iOS

Drop `/node_modules/react-native-turbolinks/ios/Turbolinks.framework` to XCode Embedded Binaries and then check `"Copy items if need"` when it is prompted.

[Install Turbolinks Framework IOS](https://raw.githubusercontent.com/lazaronixon/react-native-turbolinks/master/Example/screenshots/install-turbolinks-framework-ios.jpg)

After that check if a copy of Turbolinks.framework is in your ios project folder. If not copy it manually.

**Comment by Bickson** [comment]
yes, and the `.framework` is in iOS folder
tried to google a little ( keep in mind that this is beyond me ), can it have anything to do with the valid architectures for the `turbolinks.framework`?

**Comment by lazaronixon** [comment]
Did you run?
`npm install react-native-swift --save`

**Comment by Bickson** [comment]
yes `yarn add react-native-swift` so its in there

**Comment by Bickson** [comment]
to clarify, it works on simulator but not when I build Generic or onto phone

**Comment by lazaronixon** [comment]
Thank you I will test it

**Comment by lazaronixon** [comment]
Fixed https://github.com/lazaronixon/react-native-turbolinks/releases/tag/v1.2.8

**Comment by Bickson** [comment]
still having problem
![screen shot 2018-03-16 at 17 32 28](https://user-images.githubusercontent.com/946680/37532754-32de9e0c-2940-11e8-9102-c298e47cdc87.png)

**Comment by lazaronixon** [comment]
All is working here... I pushed a production app to App Store today.
